#!/bin/sh

lb config noauto \
    --distribution "torouter" \
    --architectures armel \
    --linux-flavours kirkwood \
    --apt-secure true \
    --binary-images hdd \
    --cache true \
    --cache-indices true \
    --cache-packages true \
    --parent-mirror-bootstrap http://http.debian.net/debian \
    --mirror-bootstrap http://http.debian.net/debian \
    --cache-stages rootfs \
    --distribution wheezy \
    --parent-distribution wheezy \
    --binary-filesystem ext3 \
    --chroot-filesystem none \
    --security true \
    --debian-installer-gui false \
    --bootstrap-qemu-arch armel \
    --bootstrap-qemu-static /usr/bin/qemu-arm-static \
    --keyring-packages "debian-archive-keyring deb.torproject.org-keyring" \
    --bootappend-live "console=ttyS0,115200 boot=live config username=torouter hostname=torouter live-media=/dev/sdb1 live-media-timeout=10 debug plainroot" \
    "${@}"

# Note: chroot filesystem should be 'squashfs' for production images (?), or
# 'none' for development (easier to modify and debug rootfs)

# Note: bootappend-live options are ignored when booting from u-boot, but are
# included here for clarity. check ../doc for most up-to-date recommended boot
# flags
