#!/bin/sh

STATEFILE=/var/lib/live/config/serialconsole

Serialconsole ()
{
	# Checking that we haven't already run
	if [ -e ${STATEFILE} ]
	then
		return
	fi
	
	echo -n " serial console"
	
	Configure_serialconsole
}

Configure_serialconsole ()
{
	# Note unusual delimiters
    # This *fixes*, but does not necessarily enable...
	sed -i -e "s|\(T0:.*\?/dev/\)\(tty\)\(.*\?/dev/\)\(tty\)\(.*\)|\1\2S0\3\4S0\5|" /etc/inittab
    tail /etc/inittab
	init q

	# Creating state file
	touch ${STATEFILE}
}

Serialconsole
